### ISSUE TITLE
Regarding  training time

### ISSUE THREAD

**Issue by swapb94** [facebookresearch/novel-view-acoustic-synthesis#2]
@ChanganVR 
Given that the model size is fairly small, with 13.8M params for the replay-nvas dataset, can you let me know how much time did it take for you train and on which GPU?
The code mentions 8 gpus with batch size of 24. But I'm confused as to why a 13M model has such huge compute requirements. 
Am I missing something? Apologies in advance if this is a trivial question!

(Is it possible to share the training log?)

![dha](https://github.com/facebookresearch/novel-view-acoustic-synthesis/assets/26220501/0700b175-04f2-4556-9e23-4917128ad1a4)

**Comment by ChanganVR** [comment]
@swapb94 The memory footprint is not only about the size of the model but also the complexity of the computation. For example, convolution layers might have few parameters but the memory can get very big if the input data is large. In this case, the audio waveform is pretty sizable and I think that's why the GPU memory consumption is high. It's definitely ok to train the model on one GPU though. I tend to use more GPUs to speed things up when possible.
